name: leanix-action-test

on:
  push:
    

env:
  HOST: eu-4.leanix.net
  LEANIX_MANIFEST_PATH: /manifest.yaml
  DEPENDENCY_MANAGER: MAVEN
  STAGE: production
  VERSION: 2.2.0
  ALLOW_FAILURE: true


jobs:
  leanix_test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: LeanIX Microservice Intelligence
        uses: leanix/github-actions-store-leanix-plugin@main
        id: LIXMI
        with:
          host: ${{ env.HOST }}
          api-token: ${{ secrets.APITOKEN }}
          manifest-path: ${{ env.LEANIX_MANIFEST_PATH }}
          dependency-manager: ${{ env.DEPENDENCY_MANAGER }}
          stage: ${{ env.STAGE }}
          version: ${{ env.VERSION }}
          allow-failure: ${{ env.ALLOW_FAILURE }}